### PR TITLE
Updated code to be compatible with Dart 2.2

### PR DESCRIPTION
**Pull request by PhilipRoman**
Hello!

I tried to use this project but I couldn't get it to compile with Dart 2.2.0. I made a fork and (hopefully) fixed the errors so I decided to make a pull request with my changes.

I had to change the compiler from `gcc` to `clang` because `gcc` could not understand `-undefined dynamic_lookup`. Maybe this is just an issue with my setup.

### CODE REVIEW

**Comment by izaera** [comment]
Hi @PhilipRoman. I'm no longer maintaining this project because I stopped using Dart long ago. If you want, I can transfer the ownership in dart's repository to you (I'm supossing that's possible), so that you can upload new versions.

Then I can archive this repository and point to yours as the official source for the package :-).

What do you think?

**Comment by PhilipRoman** [comment]
I suppose I could give it a shot. At the very least, I can keep it compatible with future Dart updates.

**Comment by izaera** [comment]
@PhilipRoman in fact, there's no need to transfer anything because I never published it in pub.dartlang.org or, at least, I cannot see it from its web search.

I'll just archive this repo and point to your fork in case anyone wants to use it and/or contribute :-)

**Comment by izaera** [comment]
I've updated the README and will now archive the repo.

Thanks @PhilipRoman :-)

**Pull request closed without merging**
